import csv
import random
import time

import requests

city_map = ['深圳','北京','上海','广州','成都']



def statis_output(title, rowlist, database,city) -> object:
    csvfile = open('{}'.format(title), 'w+', newline='', encoding='utf-8')
    res_writer = csv.writer(csvfile, dialect='excel')
    res_writer.writerow(rowlist)
    for item in database.find({'city_name':city}):
        res_writer.writerow(list(item.values())[1:])

def get_ua():
    user_agents = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36",
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 OPR/26.0.1656.60',
        'Opera/8.0 (Windows NT 5.1; U; en)',
        'Mozilla/5.0 (Windows NT 5.1; U; en; rv:1.8.1) Gecko/20061208 Firefox/2.0.0 Opera 9.50',
        'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.50',
        'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0',
        'Mozilla/5.0 (X11; U; Linux x86_64; zh-CN; rv:1.9.2.10) Gecko/20100922 Ubuntu/10.10 (maverick) Firefox/3.6.10',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.57.2 (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2 ',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36',
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
        'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.648.133 Safari/534.16',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36',
        'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.11 TaoBrowser/2.0 Safari/536.11',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.71 Safari/537.1 LBBROWSER',
        'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; QQDownload 732; .NET4.0C; .NET4.0E)',
        'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.84 Safari/535.11 SE 2.X MetaSr 1.0',
        'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; SV1; QQDownload 732; .NET4.0C; .NET4.0E; SE 2.X MetaSr 1.0) '
    ]
    user_agent = random.choice(user_agents)  # random.choice(),从列表中随机抽取一个对象
    return user_agent



def get_proxy():
    try:
        return requests.get('http://47.106.223.4:50002/get/').json().get('proxy')
    except:
        num = 3
        while num:
            try:
                return requests.get('http://47.106.223.4:50002/get/').json().get('proxy')
            except:
                print('暂无ip，等待20秒')
                time.sleep(20)

                num -= 1
        print('暂无ip')





def delete_proxy(proxy):
    html = requests.get('http://47.106.223.4:50002/delete/?proxy={}'.format(proxy))
    return html.text


city_url = {

    "滁州":"https://chuzhou.anjuke.com",
    "马鞍山":"https://maanshan.anjuke.com",
    "安庆":"https://anqing.anjuke.com",
    "蚌埠":"https://bengbu.anjuke.com",
    "巢湖":"https://chaohu.anjuke.com",
    "池州":"https://chizhou.anjuke.com",
    "阜阳":"https://fuyang.anjuke.com",
    "淮北":"https://huaibei.anjuke.com",
    "淮南":"https://huainan.anjuke.com",
    "黄山":"https://huangshan.anjuke.com",
    "六安":"https://luan.anjuke.com",
    "宿州":"https://suzhoushi.anjuke.com",
    "铜陵":"https://tongling.anjuke.com",
    "芜湖":"https://wuhu.anjuke.com",
    "宣城":"https://xuancheng.anjuke.com",
    "亳州":"https://bozhou.anjuke.com",
    "合肥":"https://hf.anjuke.com",
    "澳门":"https://aomen.anjuke.com",
    "北京":"https://beijing.anjuke.com",
    "福州":"https://fz.anjuke.com",
    "厦门":"https://xm.anjuke.com",
    "龙岩":"https://longyan.anjuke.com",
    "南平":"https://nanping.anjuke.com",
    "宁德":"https://ningde.anjuke.com",
    "莆田":"https://putian.anjuke.com",
    "泉州":"https://quanzhou.anjuke.com",
    "三明":"https://sanming.anjuke.com",
    "漳州":"https://zhangzhou.anjuke.com",
    "兰州":"https://lanzhou.anjuke.com",
    "白银":"https://baiyin.anjuke.com",
    "定西":"https://dingxi.anjuke.com",
    "甘南":"https://gannan.anjuke.com",
    "嘉峪关":"https://jiayuguan.anjuke.com",
    "金昌":"https://jinchang.anjuke.com",
    "酒泉":"https://jiuquan.anjuke.com",
    "临夏":"https://linxia.anjuke.com",
    "陇南":"https://longnan.anjuke.com",
    "平凉":"https://pingliang.anjuke.com",
    "庆阳":"https://qingyang.anjuke.com",
    "天水":"https://tianshui.anjuke.com",
    "武威":"https://wuwei.anjuke.com",
    "张掖":"https://zhangye.anjuke.com",
    "深圳":"https://shenzhen.anjuke.com",
    "东莞":"https://dg.anjuke.com",
    "惠州":"https://huizhou.anjuke.com",
    "广州":"https://guangzhou.anjuke.com",
    "佛山":"https://foshan.anjuke.com",
    "潮州":"https://chaozhou.anjuke.com",
    "河源":"https://heyuan.anjuke.com",
    "江门":"https://jiangmen.anjuke.com",
    "揭阳":"https://jieyang.anjuke.com",
    "茂名":"https://maoming.anjuke.com",
    "梅州":"https://meizhou.anjuke.com",
    "清远":"https://qingyuan.anjuke.com",
    "汕头":"https://shantou.anjuke.com",
    "汕尾":"https://shanwei.anjuke.com",
    "韶关":"https://shaoguan.anjuke.com",
    "阳江":"https://yangjiang.anjuke.com",
    "云浮":"https://yufu.anjuke.com",
    "湛江":"https://zhanjiang.anjuke.com",
    "肇庆":"https://zhaoqing.anjuke.com",
    "中山":"https://zs.anjuke.com",
    "珠海":"https://zh.anjuke.com",
    "北海":"https://beihai.anjuke.com",
    "南宁":"https://nanning.anjuke.com",
    "桂林":"https://guilin.anjuke.com",
    "百色":"https://baise.anjuke.com",
    "崇左":"https://chongzuo.anjuke.com",
    "防城港":"https://fangchenggang.anjuke.com",
    "贵港":"https://guigang.anjuke.com",
    "河池":"https://hechi.anjuke.com",
    "贺州":"https://hezhou.anjuke.com",
    "来宾":"https://laibin.anjuke.com",
    "柳州":"https://liuzhou.anjuke.com",
    "钦州":"https://qinzhou.anjuke.com",
    "梧州":"https://wuzhou.anjuke.com",
    "玉林":"https://yulinshi.anjuke.com",
    "贵阳":"https://gy.anjuke.com",
    "安顺":"https://anshun.anjuke.com",
    "毕节":"https://bijie.anjuke.com",
    "六盘水":"https://liupanshui.anjuke.com",
    "黔东南":"https://qiandongnan.anjuke.com",
    "黔南":"https://qiannan.anjuke.com",
    "黔西南":"https://qianxinan.anjuke.com",
    "铜仁":"https://tongren.anjuke.com",
    "遵义":"https://zunyi.anjuke.com",
    "海口":"https://haikou.anjuke.com",
    "三亚":"https://sanya.anjuke.com",
    "保亭":"https://sanya.anjuke.com",
    "定安":"https://haikou.anjuke.com",
    "东方":"https://dongfang.anjuke.com",
    "陵水":"https://sanya.anjuke.com",
    "琼海":"https://qionghai.anjuke.com",
    "琼中":"https://haikou.anjuke.com",
    "屯昌":"https://haikou.anjuke.com",
    "万宁":"https://wanning.anjuke.com",
    "文昌":"https://wenchang.anjuke.com",
    "五指山":"https://wuzhishan.anjuke.com",
    "儋州":"https://danzhou.anjuke.com",
    "石家庄":"https://sjz.anjuke.com",
    "保定":"https://baoding.anjuke.com",
    "沧州":"https://cangzhou.anjuke.com",
    "承德":"https://chengde.anjuke.com",
    "邯郸":"https://handan.anjuke.com",
    "衡水":"https://hengshui.anjuke.com",
    "廊坊":"https://langfang.anjuke.com",
    "秦皇岛":"https://qinhuangdao.anjuke.com",
    "唐山":"https://tangshan.anjuke.com",
    "邢台":"https://xingtai.anjuke.com",
    "张家口":"https://zhangjiakou.anjuke.com",
    "郑州":"https://zhengzhou.anjuke.com",
    "洛阳":"https://luoyang.anjuke.com",
    "开封":"https://kaifeng.anjuke.com",
    "安阳":"https://anyang.anjuke.com",
    "鹤壁":"https://hebi.anjuke.com",
    "济源":"https://jiyuan.anjuke.com",
    "焦作":"https://jiaozuo.anjuke.com",
    "南阳":"https://nanyang.anjuke.com",
    "平顶山":"https://pingdingsha.anjuke.com",
    "三门峡":"https://sanmenxia.anjuke.com",
    "商丘":"https://shangqiu.anjuke.com",
    "新乡":"https://xinxiang.anjuke.com",
    "信阳":"https://xinyang.anjuke.com",
    "许昌":"https://xuchang.anjuke.com",
    "周口":"https://zhoukou.anjuke.com",
    "驻马店":"https://zhumadian.anjuke.com",
    "漯河":"https://luohe.anjuke.com",
    "濮阳":"https://puyang.anjuke.com",
    "哈尔滨":"https://heb.anjuke.com",
    "大庆":"https://daqing.anjuke.com",
    "大兴安岭":"https://dxanling.anjuke.com",
    "鹤岗":"https://hegang.anjuke.com",
    "黑河":"https://heihe.anjuke.com",
    "鸡西":"https://jixi.anjuke.com",
    "佳木斯":"https://jiamusi.anjuke.com",
    "牡丹江":"https://mudanjiang.anjuke.com",
    "七台河":"https://qitaihe.anjuke.com",
    "齐齐哈尔":"https://qiqihaer.anjuke.com",
    "双鸭山":"https://shuangyashan.anjuke.com",
    "绥化":"https://suihua.anjuke.com",
    "伊春":"https://yichunshi.anjuke.com",
    "武汉":"https://wuhan.anjuke.com",
    "鄂州":"https://ezhou.anjuke.com",
    "孝感":"https://xiaogan.anjuke.com",
    "仙桃":"https://xiantao.anjuke.com",
    "黄冈":"https://huanggang.anjuke.com",
    "黄石":"https://huangshi.anjuke.com",
    "荆门":"https://jingmen.anjuke.com",
    "荆州":"https://jingzhou.anjuke.com",
    "潜江":"https://qianjiang.anjuke.com",
    "神农架":"https://shennongjia.anjuke.com",
    "十堰":"https://shiyan.anjuke.com",
    "随州":"https://suizhou.anjuke.com",
    "天门":"https://tianmen.anjuke.com",
    "咸宁":"https://xianning.anjuke.com",
    "襄阳":"https://xiangyang.anjuke.com",
    "宜昌":"https://yichang.anjuke.com",
    "恩施":"https://enshi.anjuke.com",
    "长沙":"https://cs.anjuke.com",
    "张家界":"https://zhangjiajie.anjuke.com",
    "常德":"https://changde.anjuke.com",
    "郴州":"https://chenzhou.anjuke.com",
    "衡阳":"https://hengyang.anjuke.com",
    "怀化":"https://huaihua.anjuke.com",
    "娄底":"https://loudi.anjuke.com",
    "邵阳":"https://shaoyang.anjuke.com",
    "湘潭":"https://xiangtan.anjuke.com",
    "湘西":"https://xiangxi.anjuke.com",
    "益阳":"https://yiyang.anjuke.com",
    "永州":"https://yongzhou.anjuke.com",
    "岳阳":"https://yueyang.anjuke.com",
    "株洲":"https://zhuzhou.anjuke.com",
    "长春":"https://cc.anjuke.com",
    "吉林":"https://jilin.anjuke.com",
    "白城":"https://baicheng.anjuke.com",
    "白山":"https://baishan.anjuke.com",
    "辽源":"https://liaoyuan.anjuke.com",
    "四平":"https://siping.anjuke.com",
    "松原":"https://songyuan.anjuke.com",
    "通化":"https://tonghua.anjuke.com",
    "延边":"https://yanbian.anjuke.com",
    "南京":"https://nanjing.anjuke.com",
    "南通":"https://nantong.anjuke.com",
    "扬州":"https://yangzhou.anjuke.com",
    "镇江":"https://zhenjiang.anjuke.com",
    "苏州":"https://suzhou.anjuke.com",
    "无锡":"https://wuxi.anjuke.com",
    "常州":"https://cz.anjuke.com",
    "淮安":"https://huaian.anjuke.com",
    "连云港":"https://lianyungang.anjuke.com",
    "宿迁":"https://suqian.anjuke.com",
    "泰州":"https://taizhou.anjuke.com",
    "徐州":"https://xuzhou.anjuke.com",
    "盐城":"https://yancheng.anjuke.com",
    "南昌":"https://nc.anjuke.com",
    "抚州":"https://fuzhoushi.anjuke.com",
    "赣州":"https://ganzhou.anjuke.com",
    "吉安":"https://jian.anjuke.com",
    "景德镇":"https://jingdezhen.anjuke.com",
    "九江":"https://jiujiang.anjuke.com",
    "萍乡":"https://pingxiang.anjuke.com",
    "上饶":"https://shangrao.anjuke.com",
    "新余":"https://xinyu.anjuke.com",
    "宜春":"https://yichun.anjuke.com",
    "鹰潭":"https://yingtan.anjuke.com",
    "沈阳":"https://sy.anjuke.com",
    "大连":"https://dalian.anjuke.com",
    "鞍山":"https://anshan.anjuke.com",
    "本溪":"https://benxi.anjuke.com",
    "朝阳":"https://chaoyang.anjuke.com",
    "丹东":"https://dandong.anjuke.com",
    "抚顺":"https://fushun.anjuke.com",
    "阜新":"https://fuxin.anjuke.com",
    "葫芦岛":"https://huludao.anjuke.com",
    "锦州":"https://jinzhou.anjuke.com",
    "辽阳":"https://liaoyang.anjuke.com",
    "盘锦":"https://panjin.anjuke.com",
    "铁岭":"https://tieling.anjuke.com",
    "营口":"https://yingkou.anjuke.com",
    "呼和浩特":"https://huhehaote.anjuke.com",
    "包头":"https://baotou.anjuke.com",
    "赤峰":"https://chifeng.anjuke.com",
    "鄂尔多斯":"https://eerduosi.anjuke.com",
    "呼伦贝尔":"https://hulunbeier.anjuke.com",
    "通辽":"https://tongliao.anjuke.com",
    "乌海":"https://wuhai.anjuke.com",
    "乌兰察布":"https://wulanchabu.anjuke.com",
    "银川":"https://yinchuan.anjuke.com",
    "固原":"https://guyuan.anjuke.com",
    "石嘴山":"https://shizuishan.anjuke.com",
    "吴忠":"https://wuzhong.anjuke.com",
    "中卫":"https://weizhong.anjuke.com",
    "西宁":"https://xining.anjuke.com",
    "果洛":"https://guoluo.anjuke.com",
    "海北":"https://haibei.anjuke.com",
    "海东":"https://haidong.anjuke.com",
    "海南":"https://hainan.anjuke.com",
    "海西":"https://hexi.anjuke.com",
    "黄南":"https://huangnan.anjuke.com",
    "玉树":"https://yushu.anjuke.com",
    "济南":"https://jinan.anjuke.com",
    "德州":"https://dezhou.anjuke.com",
    "济宁":"https://jining.anjuke.com",
    "青岛":"https://qd.anjuke.com",
    "滨州":"https://binzhou.anjuke.com",
    "东营":"https://dongying.anjuke.com",
    "菏泽":"https://heze.anjuke.com",
    "莱芜":"https://laiwu.anjuke.com",
    "聊城":"https://liaocheng.anjuke.com",
    "临沂":"https://linyi.anjuke.com",
    "日照":"https://rizhao.anjuke.com",
    "泰安":"https://taian.anjuke.com",
    "威海":"https://weihai.anjuke.com",
    "潍坊":"https://weifang.anjuke.com",
    "烟台":"https://yt.anjuke.com",
    "枣庄":"https://zaozhuang.anjuke.com",
    "淄博":"https://zibo.anjuke.com",
    "太原":"https://ty.anjuke.com",
    "长治":"https://changzhi.anjuke.com",
    "大同":"https://datong.anjuke.com",
    "晋城":"https://jincheng.anjuke.com",
    "晋中":"https://jinzhong.anjuke.com",
    "临汾":"https://linfen.anjuke.com",
    "吕梁":"https://lvliang.anjuke.com",
    "朔州":"https://shuozhou.anjuke.com",
    "忻州":"https://xinzhou.anjuke.com",
    "阳泉":"https://yangquan.anjuke.com",
    "运城":"https://yuncheng.anjuke.com",
    "西安":"https://xa.anjuke.com",
    "咸阳":"https://xianyang.anjuke.com",
    "安康":"https://ankang.anjuke.com",
    "宝鸡":"https://baoji.anjuke.com",
    "汉中":"https://hanzhong.anjuke.com",
    "商洛":"https://shangluo.anjuke.com",
    "铜川":"https://tongchuan.anjuke.com",
    "渭南":"https://weinan.anjuke.com",
    "延安":"https://yanan.anjuke.com",
    "榆林":"https://yulin.anjuke.com",
    "上海":"https://shanghai.anjuke.com",
    "成都":"https://chengdu.anjuke.com",
    "绵阳":"https://mianyang.anjuke.com",
    "阿坝":"https://aba.anjuke.com",
    "巴中":"https://bazhong.anjuke.com",
    "达州":"https://dazhou.anjuke.com",
    "德阳":"https://deyang.anjuke.com",
    "甘孜":"https://ganzi.anjuke.com",
    "广安":"https://guangan.anjuke.com",
    "广元":"https://guangyuan.anjuke.com",
    "乐山":"https://leshan.anjuke.com",
    "凉山":"https://liangshan.anjuke.com",
    "眉山":"https://meishan.anjuke.com",
    "南充":"https://nanchong.anjuke.com",
    "内江":"https://neijiang.anjuke.com",
    "攀枝花":"https://panzhihua.anjuke.com",
    "遂宁":"https://suining.anjuke.com",
    "雅安":"https://yaan.anjuke.com",
    "宜宾":"https://yibin.anjuke.com",
    "资阳":"https://ziyang.anjuke.com",
    "自贡":"https://zigong.anjuke.com",
    "泸州":"https://luzhou.anjuke.com",
    "台湾":"https://taiwan.anjuke.com",
    "天津":"https://tianjin.anjuke.com",
    "拉萨":"https://lasa.anjuke.com",
    "阿里":"https://ali.anjuke.com",
    "昌都":"https://changdu.anjuke.com",
    "林芝":"https://linzhi.anjuke.com",
    "那曲":"https://naqu.anjuke.com",
    "日喀则":"https://rikeze.anjuke.com",
    "山南":"https://shannan.anjuke.com",
    "香港":"https://xianggang.anjuke.com",
    "乌鲁木齐":"https://wulumuqi.anjuke.com",
    "阿克苏":"https://akesu.anjuke.com",
    "阿拉尔":"https://alaer.anjuke.com",
    "巴音郭楞":"https://bayinguoleng.anjuke.com",
    "博尔塔拉":"https://boertala.anjuke.com",
    "昌吉":"https://changji.anjuke.com",
    "哈密":"https://hami.anjuke.com",
    "和田":"https://hetian.anjuke.com",
    "喀什":"https://kashi.anjuke.com",
    "克拉玛依":"https://kelamayi.anjuke.com",
    "克孜勒苏":"https://lezilesu.anjuke.com",
    "石河子":"https://shihezi.anjuke.com",
    "图木舒克":"https://tumushuke.anjuke.com",
    "吐鲁番":"https://tulufan.anjuke.com",
    "五家渠":"https://wujiaqu.anjuke.com",
    "伊犁":"https://yili.anjuke.com",
    "昆明":"https://km.anjuke.com",
    "怒江":"https://nujiang.anjuke.com",
    "普洱":"https://puer.anjuke.com",
    "丽江":"https://lijiang.anjuke.com",
    "保山":"https://baoshan.anjuke.com",
    "楚雄":"https://chuxiong.anjuke.com",
    "大理":"https://dali.anjuke.com",
    "德宏":"https://dehong.anjuke.com",
    "迪庆":"https://diqing.anjuke.com",
    "红河":"https://honghe.anjuke.com",
    "临沧":"https://lingcang.anjuke.com",
    "曲靖":"https://qujing.anjuke.com",
    "文山":"https://wenshan.anjuke.com",
    "西双版纳":"https://bannan.anjuke.com",
    "玉溪":"https://yuxi.anjuke.com",
    "昭通":"https://zhaotong.anjuke.com",
    "杭州":"https://hangzhou.anjuke.com",
    "温州":"https://wenzhou.anjuke.com",
    "湖州":"https://huzhou.anjuke.com",
    "嘉兴":"https://jx.anjuke.com",
    "台州":"https://taiz.anjuke.com",
    "金华":"https://jinhua.anjuke.com",
    "丽水":"https://lishui.anjuke.com",
    "宁波":"https://nb.anjuke.com",
    "绍兴":"https://shaoxing.anjuke.com",
    "舟山":"https://zhoushan.anjuke.com",
    "衢州":"https://quzhou.anjuke.com",
    "重庆":"https://chongqing.anjuke.com"
}